version: '3.9'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27018:27017
    networks:
      myNetwork:
        ipv4_address: 172.16.0.14
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  backend:
    image: pixelwar/backend
    depends_on:
      - mongodb
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 3001:3001
    networks:
      myNetwork:
        ipv4_address: 172.16.0.15
    environment:
      - PORT=3001
      - MONGOCONNECTION=mongodb://admin:admin@mongodb:27017

  frontend:
    image: pixelwar/frontend
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 3000:3000
    networks:
      myNetwork:
        ipv4_address: 172.16.0.16
    environment:
      - PORT=3000

networks:
  myNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24